import { Link } from 'react-router-dom';
import { Clock3, HelpCircle, Mail, MapPin, MessageSquareText, Phone, ShieldCheck } from 'lucide-react';
import { Brand } from '../components/Brand.jsx';
import { Footer } from '../components/Footer.jsx';
import { useSiteSettings } from '../context/SiteSettingsContext.jsx';

export default function Contact() {
  const { settings } = useSiteSettings();
  const email = settings.supportEmail?.trim();
  const phone = settings.contactPhone?.trim();
  const mailLink = email ? `mailto:${email}?subject=${encodeURIComponent(`${settings.siteName} support request`)}` : '';
  return <div className="contact-page"><header className="public-nav"><Link to="/" aria-label={`${settings.siteName} home`}><Brand /></Link><div><Link className="text-link" to="/login">Log in</Link><Link className="button button-primary" to="/register">Create account</Link></div></header><main className="contact-main"><section className="contact-hero"><span><MessageSquareText />Support</span><h1>How can we help?</h1><p>Questions about your account, typing tests or results? Send the support team a clear note and include the details below.</p></section><div className="contact-grid"><section className="contact-primary-card"><div className="contact-icon"><Mail /></div><span>Contact support</span><h2>{email || 'Support email is being configured'}</h2><p>{email ? 'Email is the fastest way to reach the team. Your mail app will open with the subject prepared.' : 'An administrator has not added a support email yet. Please check this page again later.'}</p>{email ? <a className="button button-primary" href={mailLink}>Email support <Mail /></a> : <button className="button button-secondary" disabled>Email unavailable</button>}</section><aside className="contact-guide"><span>For a faster resolution</span><h2>Include these details</h2><ul><li><HelpCircle /><div><strong>What happened</strong><small>Describe the page, action and message you saw.</small></div></li><li><ShieldCheck /><div><strong>Your account email</strong><small>Never include your password or authentication code.</small></div></li><li><Clock3 /><div><strong>When it occurred</strong><small>Add the approximate date, time and exam name.</small></div></li></ul></aside></div>{(phone || settings.addressUrl) && <section className="contact-methods">{phone && <a href={`tel:${phone}`}><span><Phone /></span><div><small>Call us</small><strong>{phone}</strong></div></a>}{settings.addressUrl && <a href={settings.addressUrl} target="_blank" rel="noopener noreferrer"><span><MapPin /></span><div><small>Academy location</small><strong>Open in Google Maps</strong></div></a>}</section>}<section className="contact-note"><ShieldCheck /><div><strong>Protect your account</strong><p>{settings.siteName} support will never ask for your password. Share screenshots only after hiding personal or sensitive information.</p></div></section></main><Footer /></div>;
}
