import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, BarChart3, BookOpenText, CheckCircle2, FileClock, Gauge, Keyboard, Languages, Sparkles, Target } from 'lucide-react';
import { api } from '../services/api.js';
import { Loader } from '../components/Loader.jsx';
import { Notice } from '../components/Toast.jsx';
import { useAuth } from '../context/AuthContext.jsx';
import { StatCard } from '../components/dashboard/StatCard.jsx';
import { ExamCard } from '../components/dashboard/ExamCard.jsx';
import { QuickAction } from '../components/dashboard/QuickAction.jsx';

export default function Dashboard() {
  const { user } = useAuth(); const navigate = useNavigate(); const [exams, setExams] = useState([]); const [summary, setSummary] = useState({ totalTests: 0, bestWpm: 0, averageAccuracy: 0 }); const [recent, setRecent] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([api('/exams'), api('/results')]).then(([examData, resultData]) => { setExams(examData.exams); setSummary(resultData.summary); setRecent(resultData.results.slice(0, 3)); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!loading && window.location.hash === '#exams') requestAnimationFrame(() => document.getElementById('exams')?.scrollIntoView({ behavior: 'smooth' })); }, [loading]);
  const practices = useMemo(() => ({ english: exams.find((item) => item.name === 'English Typing Practice') || exams.find((item) => item.language === 'English'), hindi: exams.find((item) => item.name === 'Hindi Typing Practice') || exams.find((item) => item.language === 'Hindi') }), [exams]);
  const featuredExams = useMemo(() => exams.slice(0, 6), [exams]);
  if (loading) return <Loader label="Preparing your dashboard…" />;
  return <><section className="student-welcome"><div><span className="welcome-kicker"><Sparkles size={14} />Your practice space</span><h1>Good to see you, {user.name.split(' ')[0]}.</h1><p>Pick up where you left off and keep every keystroke intentional.</p></div><button className="welcome-action" onClick={() => document.getElementById('exams')?.scrollIntoView({ behavior: 'smooth' })}>Explore tests <ArrowRight size={18} /></button></section><Notice>{error}</Notice>
    <section className="student-stats" aria-label="Performance summary"><StatCard icon={FileClock} label="Total tests taken" value={summary.totalTests} tone="blue" /><StatCard icon={Gauge} label="Best net speed" value={`${summary.bestWpm} WPM`} tone="violet" /><StatCard icon={Target} label="Average accuracy" value={`${summary.averageAccuracy}%`} tone="green" /><StatCard icon={BookOpenText} label="Available exams" value={exams.length} tone="amber" /></section>
    <div className="dashboard-columns"><section><div className="section-heading"><div><span>Shortcuts</span><h2>Quick actions</h2></div></div><div className="quick-actions"><QuickAction to="/exams" icon={Keyboard} label="Start new test" detail="Choose any exam" /><QuickAction to={practices.english ? `/test/${practices.english._id}` : '/exams'} icon={Languages} label="Practice English" detail="Build rhythm and speed" tone="violet" /><QuickAction to={practices.hindi ? `/test/${practices.hindi._id}` : '/exams'} icon={Languages} label="Practice Hindi" detail="Improve Hindi accuracy" tone="green" /><QuickAction to="/results" icon={BarChart3} label="View results" detail="Review past attempts" tone="amber" /></div></section>
      <section><div className="section-heading"><div><span>Latest activity</span><h2>Recent results</h2></div>{recent.length > 0 && <button onClick={() => navigate('/results')}>View all <ArrowRight /></button>}</div>{recent.length ? <div className="recent-results">{recent.map((result) => <button key={result._id} onClick={() => navigate(`/result/${result._id}`)}><span className="recent-result-icon"><CheckCircle2 /></span><span><strong>{result.exam?.name || 'Typing test'}</strong><small>{new Date(result.createdAt).toLocaleDateString(undefined, { day: 'numeric', month: 'short' })}</small></span><b>{result.netWpm}<small> WPM</small></b></button>)}</div> : <div className="dashboard-empty"><span><Keyboard /></span><div><strong>Your first result starts here</strong><p>Complete a typing test and your performance summary will appear in this space.</p></div><button onClick={() => document.getElementById('exams')?.scrollIntoView({ behavior: 'smooth' })}>Take a test</button></div>}</section></div>
    <section id="exams" className="available-exams"><div className="section-heading"><div><span>Featured tests</span><h2>Popular exams</h2><p>Start with one of these exam-style typing tests.</p></div><span className="exam-count">Showing {Math.min(6, exams.length)} of {exams.length}</span></div><div className="student-exam-grid">{featuredExams.map((exam) => <ExamCard key={exam._id} exam={exam} onStart={() => navigate(`/test/${exam._id}`)} />)}</div>{!exams.length && <div className="dashboard-empty"><span><Keyboard /></span><div><strong>No active exams right now</strong><p>Your administrator is preparing new tests. Please check again shortly.</p></div></div>}{exams.length > 6 && <div className="show-more-exams"><button className="button button-secondary" onClick={() => navigate('/exams')}>Show more exams <ArrowRight /></button></div>}</section>
    <section className="dashboard-growth"><div className="section-heading"><div><span>Know your test experience</span><h2>The right interface, selected automatically</h2><p>Actual exams open in their official-style environment; only Practice lets you customize.</p></div></div><div className="test-experience-grid"><article className="experience-card experience-tcs"><div className="experience-card-head"><span>TCS</span><small>SSC exams</small></div><h3>Focused SSC interface</h3><p>SSC-related tests launch directly in TCS Mode with exam-controlled behavior and zero setup clicks.</p><ul><li><CheckCircle2 />Automatic mode selection</li><li><CheckCircle2 />Fixed exam configuration</li></ul></article><article className="experience-card experience-nta"><div className="experience-card-head"><span>NTA</span><small>Non-SSC exams</small></div><h3>Clean CBT-style workspace</h3><p>DSSSB, Railway, AIIMS, Courts and other organizations automatically use the NTA experience.</p><ul><li><CheckCircle2 />Organization-aware launch</li><li><CheckCircle2 />No manual mode popup</li></ul></article><article className="experience-card experience-practice"><div className="experience-card-head"><span>Custom</span><small>Practice only</small></div><h3>Your personal practice lab</h3><p>Adjust timer, backspace, sounds, font size, highlighting, auto-scroll and theme before practising.</p><ul><li><CheckCircle2 />Flexible preferences</li><li><CheckCircle2 />Exam modes stay unaffected</li></ul></article><aside className="readiness-card"><span className="review-kicker">Before you begin</span><h3>Quick readiness check</h3><ol><li><b>01</b><span><strong>Settle your posture</strong><small>Keep wrists relaxed and screen comfortably aligned.</small></span></li><li><b>02</b><span><strong>Read the first line</strong><small>Understand the paragraph rhythm before typing.</small></span></li><li><b>03</b><span><strong>Protect accuracy</strong><small>Build speed naturally instead of forcing the first minute.</small></span></li></ol></aside></div></section></>;
}
